//
//  StatEvent+Extensions.swift
//  MyKidStats
//
//  Created by Philip Butler on 1/24/26.
//

import Foundation
import CoreData

// Note: This extension will be populated once the Core Data model is created
// The StatEvent entity will be auto-generated by Core Data with Codegen set to "Class Definition"

extension StatEvent {
    
    var isPointEvent: Bool {
        guard let type = StatType(rawValue: statType) else { return false }
        return type.pointValue > 0
    }
}
