import Foundation
import CoreData

// MARK: - Extensions for Auto-Generated Core Data Classes
// Note: The base classes are auto-generated by Core Data with Codegen = "Class Definition"
// These extensions add computed properties and helper methods

extension Game {
    // Computed property to calculate team score from stat events
    var teamScore: Int32 {
        guard let events = statEvents as? Set<StatEvent> else { return 0 }
        let score = events.filter { !$0.isSoftDeleted }
            .reduce(0) { $0 + Int($1.value) }
        return Int32(score)
    }
}

extension StatEvent {
    // Convenience property for backwards compatibility
    // Note: The Core Data attribute is named 'isSoftDeleted'
    var isSoftDeleted: Bool {
        get { isDelete }
        set { isDelete = newValue }
    }
}

