//
//  Team+Extensions.swift
//  MyKidStats
//
//  Created by Philip Butler on 1/24/26.
//

import Foundation
import CoreData

// Note: This extension will be populated once the Core Data model is created
// The Team entity will be auto-generated by Core Data with Codegen set to "Class Definition"

extension Team {
    
    /// Find active team for a specific child
    static func fetchActive(forChildId childId: UUID, context: NSManagedObjectContext) -> Team? {
        let playerRequest = Player.fetchRequest()
        playerRequest.predicate = NSPredicate(format: "childId == %@", childId as CVarArg)
        
        guard let players = try? context.fetch(playerRequest) else { return nil }
        
        return players.first { player in
            player.team?.isActive == true
        }?.team
    }
    
    /// Deactivate all teams, activate this one
    func makeActive(context: NSManagedObjectContext) throws {
        let allTeams = try context.fetch(Team.fetchRequest())
        allTeams.forEach { $0.isActive = false }
        self.isActive = true
        try context.save()
    }
}
