//
//  Player+Extensions.swift
//  MyKidStats
//
//  Created by Philip Butler on 1/24/26.
//

import Foundation
import CoreData

// Note: This extension will be populated once the Core Data model is created
// The Player entity will be auto-generated by Core Data with Codegen set to "Class Definition"

extension Player {
    
    /// Fetch all player instances for a specific child
    static func fetchForChild(_ childId: UUID, context: NSManagedObjectContext) -> [Player] {
        let request = Player.fetchRequest()
        request.predicate = NSPredicate(format: "childId == %@", childId as CVarArg)
        return (try? context.fetch(request)) ?? []
    }
    
    /// Fetch player instance for child on specific team
    static func fetch(childId: UUID, teamId: UUID, context: NSManagedObjectContext) -> Player? {
        let request = Player.fetchRequest()
        request.predicate = NSPredicate(
            format: "childId == %@ AND teamId == %@",
            childId as CVarArg,
            teamId as CVarArg
        )
        request.fetchLimit = 1
        return try? context.fetch(request).first
    }
}
