//
//  Game+Extensions.swift
//  MyKidStats
//
//  Created by Philip Butler on 1/24/26.
//

import Foundation
import CoreData

enum GameResult: String {
    case win = "W"
    case loss = "L"
    case tie = "T"
    case inProgress = "IP"
    
    var emoji: String {
        switch self {
        case .win: return "✓"
        case .loss: return "✗"
        case .tie: return "–"
        case .inProgress: return "IP"
        }
    }
}

// Note: This extension will be populated once the Core Data model is created
// The Game entity will be auto-generated by Core Data with Codegen set to "Class Definition"

extension Game {
    
    /// Computed team score from stat events
    var calculatedTeamScore: Int {
        guard let events = statEvents as? Set<StatEvent> else { return 0 }
        return events
            .filter { $0.isPointEvent && !$0.isDelete }
            .reduce(0) { $0 + Int($1.value) }
    }
    
    /// Game result
    var result: GameResult {
        guard isComplete else { return .inProgress }
        if calculatedTeamScore > opponentScore { return .win }
        if calculatedTeamScore < opponentScore { return .loss }
        return .tie
    }
}
