//
//  Child+Extensions.swift
//  MyKidStats
//
//  Created by Philip Butler on 1/24/26.
//

import Foundation
import CoreData

// Note: This extension will be populated once the Core Data model is created
// The Child entity will be auto-generated by Core Data with Codegen set to "Class Definition"

extension Child {
    
    /// Fetch the most recently used child for smart defaults
    static func fetchLastUsed(context: NSManagedObjectContext) -> Child? {
        let request: NSFetchRequest<Child> = NSFetchRequest(entityName: "Child")
        request.sortDescriptors = [NSSortDescriptor(key: "lastUsed", ascending: false)]
        request.fetchLimit = 1
        return (try? context.fetch(request))?.first
    }
    
    /// Fetch all children sorted by name
    static func fetchAll(context: NSManagedObjectContext) -> [Child] {
        let request: NSFetchRequest<Child> = NSFetchRequest(entityName: "Child")
        request.sortDescriptors = [NSSortDescriptor(key: "name", ascending: true)]
        return (try? context.fetch(request)) ?? []
    }
    
    /// Update last used timestamp (call when starting a game)
    func markAsUsed(context: NSManagedObjectContext) throws {
        self.lastUsed = Date()
        try context.save()
    }
}
