import Foundation
import CoreData

// MARK: - Extensions for Auto-Generated Core Data Classes
// Note: The base classes are auto-generated by Core Data with Codegen = "Class Definition"
// These extensions add computed properties and helper methods

// Note: StatEvent uses the Core Data attribute 'isSoftDeleted' for soft-delete functionality
// No computed property needed - access 'isSoftDeleted' directly

